# ============================================================
# bulgarian_morphology.fst
# Generated by generate_fst_bg.py using Stanza
# ============================================================

STATE start START

# shared final states - same names as English so FSTLoader works identically
STATE n_end  FINAL
STATE v_end  FINAL
STATE fw_end FINAL


# === PRONOUNS ===
STATE fw_az
TRANSITION start fw_az "az" "az"
TRANSITION fw_az fw_end EPS "+PRON+1SG.SUBJ"
STATE fw_men
TRANSITION start fw_men "men" "men"
TRANSITION fw_men fw_end EPS "+PRON+1SG.OBJ"
STATE fw_me
TRANSITION start fw_me "me" "me"
TRANSITION fw_me fw_end EPS "+PRON+1SG.OBJ"
STATE fw_nie
TRANSITION start fw_nie "nie" "nie"
TRANSITION fw_nie fw_end EPS "+PRON+1PL.SUBJ"
STATE fw_nas
TRANSITION start fw_nas "nas" "nas"
TRANSITION fw_nas fw_end EPS "+PRON+1PL.OBJ"
STATE fw_ni
TRANSITION start fw_ni "ni" "ni"
TRANSITION fw_ni fw_end EPS "+PRON+1PL.OBJ"
STATE fw_ti
TRANSITION start fw_ti "ti" "ti"
TRANSITION fw_ti fw_end EPS "+PRON+2SG.SUBJ"
STATE fw_tebe
TRANSITION start fw_tebe "tebe" "tebe"
TRANSITION fw_tebe fw_end EPS "+PRON+2SG.OBJ"
STATE fw_te
TRANSITION start fw_te "te" "te"
TRANSITION fw_te fw_end EPS "+PRON+2SG.OBJ"
STATE fw_vie
TRANSITION start fw_vie "vie" "vie"
TRANSITION fw_vie fw_end EPS "+PRON+2PL.SUBJ"
STATE fw_vas
TRANSITION start fw_vas "vas" "vas"
TRANSITION fw_vas fw_end EPS "+PRON+2PL.OBJ"
STATE fw_vi
TRANSITION start fw_vi "vi" "vi"
TRANSITION fw_vi fw_end EPS "+PRON+2PL.OBJ"
STATE fw_toy
TRANSITION start fw_toy "toy" "toy"
TRANSITION fw_toy fw_end EPS "+PRON+3SG.M.SUBJ"
STATE fw_nego
TRANSITION start fw_nego "nego" "nego"
TRANSITION fw_nego fw_end EPS "+PRON+3SG.M.OBJ"
STATE fw_go
TRANSITION start fw_go "go" "go"
TRANSITION fw_go fw_end EPS "+PRON+3SG.M.OBJ"
STATE fw_tya
TRANSITION start fw_tya "tya" "tya"
TRANSITION fw_tya fw_end EPS "+PRON+3SG.F.SUBJ"
STATE fw_neya
TRANSITION start fw_neya "neya" "neya"
TRANSITION fw_neya fw_end EPS "+PRON+3SG.F.OBJ"
STATE fw_ya
TRANSITION start fw_ya "ya" "ya"
TRANSITION fw_ya fw_end EPS "+PRON+3SG.F.OBJ"
STATE fw_to
TRANSITION start fw_to "to" "to"
TRANSITION fw_to fw_end EPS "+PRON+3SG.N.SUBJ"
STATE fw_teh
TRANSITION start fw_teh "teh" "teh"
TRANSITION fw_teh fw_end EPS "+PRON+3PL.OBJ"
STATE fw_gi
TRANSITION start fw_gi "gi" "gi"
TRANSITION fw_gi fw_end EPS "+PRON+3PL.OBJ"
STATE fw_tozi
TRANSITION start fw_tozi "tozi" "tozi"
TRANSITION fw_tozi fw_end EPS "+PRON+DEM.M"
STATE fw_tazi
TRANSITION start fw_tazi "tazi" "tazi"
TRANSITION fw_tazi fw_end EPS "+PRON+DEM.F"
STATE fw_tova
TRANSITION start fw_tova "tova" "tova"
TRANSITION fw_tova fw_end EPS "+PRON+DEM.N"
STATE fw_tezi
TRANSITION start fw_tezi "tezi" "tezi"
TRANSITION fw_tezi fw_end EPS "+PRON+DEM.PL"
STATE fw_koj
TRANSITION start fw_koj "koj" "koj"
TRANSITION fw_koj fw_end EPS "+PRON+REL.M"
STATE fw_koya
TRANSITION start fw_koya "koya" "koya"
TRANSITION fw_koya fw_end EPS "+PRON+REL.F"
STATE fw_koe
TRANSITION start fw_koe "koe" "koe"
TRANSITION fw_koe fw_end EPS "+PRON+REL.N"
STATE fw_koi
TRANSITION start fw_koi "koi" "koi"
TRANSITION fw_koi fw_end EPS "+PRON+REL.PL"

# === PREPOSITIONS ===
STATE fw_v
TRANSITION start fw_v "v" "v"
TRANSITION fw_v fw_end EPS "+PREP+BASE"
STATE fw_vav
TRANSITION start fw_vav "vav" "vav"
TRANSITION fw_vav fw_end EPS "+PREP+BASE"
STATE fw_na
TRANSITION start fw_na "na" "na"
TRANSITION fw_na fw_end EPS "+PREP+BASE"
STATE fw_za
TRANSITION start fw_za "za" "za"
TRANSITION fw_za fw_end EPS "+PREP+BASE"
STATE fw_ot
TRANSITION start fw_ot "ot" "ot"
TRANSITION fw_ot fw_end EPS "+PREP+BASE"
STATE fw_do
TRANSITION start fw_do "do" "do"
TRANSITION fw_do fw_end EPS "+PREP+BASE"
STATE fw_kam
TRANSITION start fw_kam "kam" "kam"
TRANSITION fw_kam fw_end EPS "+PREP+BASE"
STATE fw_pri
TRANSITION start fw_pri "pri" "pri"
TRANSITION fw_pri fw_end EPS "+PREP+BASE"
STATE fw_pod
TRANSITION start fw_pod "pod" "pod"
TRANSITION fw_pod fw_end EPS "+PREP+BASE"
STATE fw_nad
TRANSITION start fw_nad "nad" "nad"
TRANSITION fw_nad fw_end EPS "+PREP+BASE"
STATE fw_bez
TRANSITION start fw_bez "bez" "bez"
TRANSITION fw_bez fw_end EPS "+PREP+BASE"
STATE fw_sled
TRANSITION start fw_sled "sled" "sled"
TRANSITION fw_sled fw_end EPS "+PREP+BASE"
STATE fw_predi
TRANSITION start fw_predi "predi" "predi"
TRANSITION fw_predi fw_end EPS "+PREP+BASE"
STATE fw_mezhdu
TRANSITION start fw_mezhdu "mezhdu" "mezhdu"
TRANSITION fw_mezhdu fw_end EPS "+PREP+BASE"
STATE fw_okolo
TRANSITION start fw_okolo "okolo" "okolo"
TRANSITION fw_okolo fw_end EPS "+PREP+BASE"
STATE fw_chrez
TRANSITION start fw_chrez "chrez" "chrez"
TRANSITION fw_chrez fw_end EPS "+PREP+BASE"
STATE fw_s
TRANSITION start fw_s "s" "s"
TRANSITION fw_s fw_end EPS "+PREP+BASE"
STATE fw_sas
TRANSITION start fw_sas "sas" "sas"
TRANSITION fw_sas fw_end EPS "+PREP+BASE"
STATE fw_po
TRANSITION start fw_po "po" "po"
TRANSITION fw_po fw_end EPS "+PREP+BASE"
STATE fw_pred
TRANSITION start fw_pred "pred" "pred"
TRANSITION fw_pred fw_end EPS "+PREP+BASE"
STATE fw_zad
TRANSITION start fw_zad "zad" "zad"
TRANSITION fw_zad fw_end EPS "+PREP+BASE"

# === CONJUNCTIONS ===
STATE fw_i
TRANSITION start fw_i "i" "i"
TRANSITION fw_i fw_end EPS "+CONJ+BASE"
STATE fw_ili
TRANSITION start fw_ili "ili" "ili"
TRANSITION fw_ili fw_end EPS "+CONJ+BASE"
STATE fw_no
TRANSITION start fw_no "no" "no"
TRANSITION fw_no fw_end EPS "+CONJ+BASE"
STATE fw_a
TRANSITION start fw_a "a" "a"
TRANSITION fw_a fw_end EPS "+CONJ+BASE"
STATE fw_che
TRANSITION start fw_che "che" "che"
TRANSITION fw_che fw_end EPS "+CONJ+BASE"
STATE fw_ako
TRANSITION start fw_ako "ako" "ako"
TRANSITION fw_ako fw_end EPS "+CONJ+BASE"
STATE fw_kogato
TRANSITION start fw_kogato "kogato" "kogato"
TRANSITION fw_kogato fw_end EPS "+CONJ+BASE"
STATE fw_zashtoto
TRANSITION start fw_zashtoto "zashtoto" "zashtoto"
TRANSITION fw_zashtoto fw_end EPS "+CONJ+BASE"
STATE fw_makar
TRANSITION start fw_makar "makar" "makar"
TRANSITION fw_makar fw_end EPS "+CONJ+BASE"
STATE fw_dali
TRANSITION start fw_dali "dali" "dali"
TRANSITION fw_dali fw_end EPS "+CONJ+BASE"
STATE fw_nito
TRANSITION start fw_nito "nito" "nito"
TRANSITION fw_nito fw_end EPS "+CONJ+BASE"
STATE fw_obache
TRANSITION start fw_obache "obache" "obache"
TRANSITION fw_obache fw_end EPS "+CONJ+BASE"

# === AUXILIARIES ===
STATE fw_sam
TRANSITION start fw_sam "sam" "sam"
TRANSITION fw_sam fw_end EPS "+AUX+1SG.PRES"
STATE fw_si
TRANSITION start fw_si "si" "si"
TRANSITION fw_si fw_end EPS "+AUX+2SG.PRES"
STATE fw_e
TRANSITION start fw_e "e" "e"
TRANSITION fw_e fw_end EPS "+AUX+3SG.PRES"
STATE fw_sme
TRANSITION start fw_sme "sme" "sme"
TRANSITION fw_sme fw_end EPS "+AUX+1PL.PRES"
STATE fw_ste
TRANSITION start fw_ste "ste" "ste"
TRANSITION fw_ste fw_end EPS "+AUX+2PL.PRES"
STATE fw_sa
TRANSITION start fw_sa "sa" "sa"
TRANSITION fw_sa fw_end EPS "+AUX+3PL.PRES"
STATE fw_byah
TRANSITION start fw_byah "byah" "byah"
TRANSITION fw_byah fw_end EPS "+AUX+1SG.PAST"
STATE fw_beshe
TRANSITION start fw_beshe "beshe" "beshe"
TRANSITION fw_beshe fw_end EPS "+AUX+3SG.PAST"
STATE fw_byaha
TRANSITION start fw_byaha "byaha" "byaha"
TRANSITION fw_byaha fw_end EPS "+AUX+3PL.PAST"
STATE fw_shte
TRANSITION start fw_shte "shte" "shte"
TRANSITION fw_shte fw_end EPS "+AUX+FUT"
STATE fw_ne
TRANSITION start fw_ne "ne" "ne"
TRANSITION fw_ne fw_end EPS "+NEG+BASE"
STATE fw_se
TRANSITION start fw_se "se" "se"
TRANSITION fw_se fw_end EPS "+REFL"

# === NOUNS ===

# === VERBS ===

# === ADJECTIVES ===
